# Generated by Django 5.0.6 on 2024-07-25 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blockquote',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
